spring:
  application:
    name: shop-app
  datasource:
    password: root
    username: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
server:
  port: 8004

mybatis-plus:
  global-config:
    db-config:
      table-prefix: shop_